# @format

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "gcr.io/erake-traning/express-app",
        "-f",
        "Dockerfile",
        ".",
      ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/erake-traning/express-app"]
    # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "training-erake",
        "--image",
        "gcr.io/erake-traning/express-app",
        "--region",
        "us-central1",
        "--project",
        "erake-traning",
      ]
images:
  - gcr.io/erake-traning/express-app
